#!/bin/bash

echo "================================================"
echo "  Expense Tracker - Fix Applied!"
echo "================================================"
echo ""
echo "I found TWO issues:"
echo ""
echo "1. ❌ You were missing 'Bearer ' in your Authorization header"
echo "   Your command: -H \"Authorization: TOKEN\""
echo "   Correct:      -H \"Authorization: Bearer TOKEN\""
echo ""
echo "2. ❌ The JWT filter wasn't setting Spring Security context"
echo "   (I fixed this in the code)"
echo ""
echo "================================================"
echo ""
echo "TO FIX - Follow these steps:"
echo ""
echo "1. STOP your current application (Ctrl+C in the other terminal)"
echo ""
echo "2. RESTART with these commands:"
echo "   cd /Users/adebay/Documents/expense_tracker"
echo "   mvn clean compile"
echo "   mvn spring-boot:run"
echo ""
echo "3. Wait for 'Started ExpenseTrackerApplication'"
echo ""
echo "4. TEST in a NEW terminal:"
echo "   cd /Users/adebay/Documents/expense_tracker"
echo "   ./test-api-simple.sh"
echo ""
echo "================================================"
echo ""
echo "Quick test after restart:"
echo ""
echo "# 1. Check API is running"
echo "curl http://localhost:8080/api/"
echo ""
echo "# 2. Register and get token"
echo "curl -X POST http://localhost:8080/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\":\"test@example.com\",\"password\":\"TestPass123\"}'"
echo ""
echo "# 3. Use token (with Bearer prefix!)"
echo "curl http://localhost:8080/api/dashboard \\"
echo "  -H \"Authorization: Bearer YOUR_TOKEN\""
echo ""
echo "================================================"
echo ""
echo "For detailed help, see: AUTHENTICATION_FIX.md"
echo ""

